// ExerciseDB 真人动作 GIF（连贯动画，Keep 式演示）
// 来源：static.exercisedb.dev 官方 CDN（ExerciseDB v1；media © 原版权方，仅限个人学习/非商用）
// 生成：node scripts/build_gif_map.js（先 --fetch 全量数据，再按 PICK 精校表输出）
module.exports = {
  "卷腹": "https://cdn.jsdelivr.net/gh/sovanndevid/my-exercisedb@main/media/TFqbd8t.gif",
  "俄罗斯转体": "https://cdn.jsdelivr.net/gh/sovanndevid/my-exercisedb@main/media/XVDdcoj.gif",
  "仰卧交替抬腿": "https://cdn.jsdelivr.net/gh/sovanndevid/my-exercisedb@main/media/UVo2Qs2.gif",
  "左侧平板": "https://cdn.jsdelivr.net/gh/sovanndevid/my-exercisedb@main/media/5VXmnV5.gif",
  "右侧平板": "https://cdn.jsdelivr.net/gh/sovanndevid/my-exercisedb@main/media/5VXmnV5.gif",
  "开合跳": "https://cdn.jsdelivr.net/gh/sovanndevid/my-exercisedb@main/media/1g5bPpA.gif",
  "高抬腿": "https://cdn.jsdelivr.net/gh/sovanndevid/my-exercisedb@main/media/ealLwvX.gif",
  "波比跳": "https://cdn.jsdelivr.net/gh/sovanndevid/my-exercisedb@main/media/dK9394r.gif",
  "登山者": "https://cdn.jsdelivr.net/gh/sovanndevid/my-exercisedb@main/media/RJgzwny.gif",
  "深蹲跳": "https://cdn.jsdelivr.net/gh/sovanndevid/my-exercisedb@main/media/6FMU51h.gif",
  "仰卧起坐": "https://cdn.jsdelivr.net/gh/sovanndevid/my-exercisedb@main/media/2gPfomN.gif",
  "弓步蹲": "https://cdn.jsdelivr.net/gh/sovanndevid/my-exercisedb@main/media/IZVHb27.gif",
  "箭步蹲": "https://cdn.jsdelivr.net/gh/sovanndevid/my-exercisedb@main/media/kMzUs9Y.gif",
  "标准俯卧撑": "https://cdn.jsdelivr.net/gh/sovanndevid/my-exercisedb@main/media/I4hDWkc.gif",
  "钻石俯卧撑": "https://cdn.jsdelivr.net/gh/sovanndevid/my-exercisedb@main/media/soIB2rj.gif",
  "窄距俯卧撑": "https://cdn.jsdelivr.net/gh/sovanndevid/my-exercisedb@main/media/x6KpKpq.gif",
  "上斜俯卧撑": "https://cdn.jsdelivr.net/gh/sovanndevid/my-exercisedb@main/media/B1EVP9F.gif",
  "等长收缩": "https://cdn.jsdelivr.net/gh/sovanndevid/my-exercisedb@main/media/HbSG1Pw.gif",
  "哑铃飞鸟": "https://cdn.jsdelivr.net/gh/sovanndevid/my-exercisedb@main/media/yz9nUhF.gif",
  "哑铃卧推": "https://cdn.jsdelivr.net/gh/sovanndevid/my-exercisedb@main/media/SpYC0Kp.gif",
  "哑铃肩推": "https://cdn.jsdelivr.net/gh/sovanndevid/my-exercisedb@main/media/A6wtbuL.gif",
  "哑铃侧平举": "https://cdn.jsdelivr.net/gh/sovanndevid/my-exercisedb@main/media/DsgkuIt.gif",
  "哑铃划船": "https://cdn.jsdelivr.net/gh/sovanndevid/my-exercisedb@main/media/ZIViNh1.gif",
  "弹力带下拉": "https://cdn.jsdelivr.net/gh/sovanndevid/my-exercisedb@main/media/DptumMx.gif",
  "引体向上": "https://cdn.jsdelivr.net/gh/sovanndevid/my-exercisedb@main/media/r1XNRYB.gif",
  "弹力带面拉": "https://cdn.jsdelivr.net/gh/sovanndevid/my-exercisedb@main/media/tc5dYrf.gif",
  "锤式弯举": "https://cdn.jsdelivr.net/gh/sovanndevid/my-exercisedb@main/media/slDvUAU.gif",
  "高脚杯深蹲": "https://cdn.jsdelivr.net/gh/sovanndevid/my-exercisedb@main/media/yn8yg1r.gif",
  "哑铃硬拉": "https://cdn.jsdelivr.net/gh/sovanndevid/my-exercisedb@main/media/nUwVh7b.gif",
  "壶铃摇摆": "https://cdn.jsdelivr.net/gh/sovanndevid/my-exercisedb@main/media/UHJlbu3.gif",
  "保加利亚分腿蹲": "https://cdn.jsdelivr.net/gh/sovanndevid/my-exercisedb@main/media/gGNQmVt.gif",
  "深蹲": "https://cdn.jsdelivr.net/gh/sovanndevid/my-exercisedb@main/media/75Bgtjy.gif",
  "臀桥": "https://cdn.jsdelivr.net/gh/sovanndevid/my-exercisedb@main/media/u0cNiij.gif",
  "仰卧举腿": "https://cdn.jsdelivr.net/gh/sovanndevid/my-exercisedb@main/media/9IxJdtC.gif",
  "死虫式": "https://cdn.jsdelivr.net/gh/sovanndevid/my-exercisedb@main/media/iny3m5y.gif",
  "弓步跳": "https://cdn.jsdelivr.net/gh/sovanndevid/my-exercisedb@main/media/PM1PZjg.gif",
  "下斜俯卧撑": "https://cdn.jsdelivr.net/gh/sovanndevid/my-exercisedb@main/media/i5cEhka.gif",
  "屈膝礼蹲": "https://cdn.jsdelivr.net/gh/sovanndevid/my-exercisedb@main/media/gUjqdei.gif",
  "臀桥踏步": "https://cdn.jsdelivr.net/gh/sovanndevid/my-exercisedb@main/media/GibBPPg.gif",
  "站姿提踵": "https://cdn.jsdelivr.net/gh/sovanndevid/my-exercisedb@main/media/bJYHBIN.gif",
  "速滑跳": "https://cdn.jsdelivr.net/gh/sovanndevid/my-exercisedb@main/media/zfNHMN9.gif",
  "肩胸拉伸": "https://cdn.jsdelivr.net/gh/sovanndevid/my-exercisedb@main/media/Uto7l43.gif",
  "仰卧臀腿拉伸": "https://cdn.jsdelivr.net/gh/sovanndevid/my-exercisedb@main/media/yn0LjwL.gif",
  "仰卧梨状肌拉伸": "https://cdn.jsdelivr.net/gh/sovanndevid/my-exercisedb@main/media/RQNVT10.gif",
  "蝴蝶式": "https://cdn.jsdelivr.net/gh/sovanndevid/my-exercisedb@main/media/bWlZvXh.gif",
  "俯卧大腿前侧拉伸": "https://cdn.jsdelivr.net/gh/sovanndevid/my-exercisedb@main/media/YUYAMEj.gif",
  "俯卧腿后侧拉伸": "https://cdn.jsdelivr.net/gh/sovanndevid/my-exercisedb@main/media/VedGSby.gif",
  "侧卧大腿内侧拉伸": "https://cdn.jsdelivr.net/gh/sovanndevid/my-exercisedb@main/media/hC6oYY5.gif"
};
