// 自动生成, 请勿手改。由 scripts/download_media.js 依据 media_map.js 下载生成。
module.exports = {
  "卷腹": "/assets/actions/91.png",
  "平板支撑": "/assets/actions/458.png",
  "俄罗斯转体": "/assets/actions/1193.png",
  "仰卧抬腿": "/assets/actions/125.png",
  "仰卧交替抬腿": "/assets/actions/125.png",
  "左侧平板": "/assets/actions/2509.png",
  "右侧平板": "/assets/actions/2509.png",
  "开合跳": "/assets/actions/320.png",
  "高抬腿": "/assets/actions/983.png",
  "仰卧起坐": "/assets/actions/1479.png",
  "弓步蹲": "/assets/actions/984.jpg",
  "箭步蹲": "/assets/actions/984.jpg",
  "婴儿式": "/assets/actions/1002.png",
  "标准俯卧撑": "/assets/actions/1551.jpg",
  "钻石俯卧撑": "/assets/actions/1551.jpg",
  "宽距俯卧撑": "/assets/actions/1551.jpg",
  "上斜俯卧撑": "/assets/actions/1551.jpg",
  "窄距俯卧撑": "/assets/actions/1551.jpg",
  "等长收缩": "/assets/actions/1733.jpg",
  "水瓶飞鸟": "/assets/actions/238.jpg",
  "深蹲": "/assets/actions/203.jpg",
  "深蹲跳": "/assets/actions/203.jpg",
  "臀桥": "/assets/actions/265.png",
  "跪姿后抬腿": "/assets/actions/1616.jpg",
  "后踢腿": "/assets/actions/990.png",
  "原地踏步": "/assets/actions/1965.png"
};
